server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  database: 'task_management'

jwt:
  expiresIn: 3600

solr:
  host: 'localhost'
  port: 8983
  path: '/solr'
  core: task

redis:
  port: 6379