version: '3'

services:
  postgres:
    image: postgres:alpine
    # volumes:
      # - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'task_management'

  mongo:
    image: mongo:bionic
    environment:
      MONGO_INITDB_DATABASE: 'phone-book'
      MONGO_INITDB_ROOT_USERNAME: 'mongo'
      MONGO_INITDB_ROOT_PASSWORD: 'mongo'
      MONGO_LOG_DIR: /dev/null
    volumes:
    # - ./mongo_data:/data/db
      - ./mongo_data/config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

  front:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./webapp_data/static:/static
      - ./webapp_data/config/nginx.conf:/etc/nginx/nginx.conf

  solrsevice:
    image: solr:latest
    ports: 
      - 8983:8983
    volumes:
      - ./solr_data:/solrhome
    command: solr start -f -s /solrhome -t /solrhome/solrindex